language: node_js
node_js:
  - "0.12"


after_success:
 - wget https://dumps.wikimedia.org/enwiktionary/latest/enwiktionary-latest-pages-articles-multistream.xml.bz2
 - bzip2 -d
 - ls
 - ./index.js enwiktionary-latest-pages-articles-multistream.xml